apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: 'kubenews'
            - name: POSTGRES_USER
              value: 'kubenews'
            - name: POSTGRES_PASSWORD
              value: 'Pg#123'
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: mauriciotp/kube-news:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_DATABASE
              value: 'kubenews'
            - name: DB_USERNAME
              value: 'kubenews'
            - name: DB_PASSWORD
              value: 'Pg#123'
            - name: DB_HOST
              value: 'postgres-service'
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
